name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run tests
        run: go test ./...

      - name: Build binaries
        run: |
          mkdir -p dist

          # Linux amd64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/loganalyzer-linux-amd64 main.go

          # Linux arm64
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/loganalyzer-linux-arm64 main.go

          # macOS amd64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/loganalyzer-darwin-amd64 main.go

          # macOS arm64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/loganalyzer-darwin-arm64 main.go

          # Windows amd64
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/loganalyzer-windows-amd64.exe main.go

      - name: Create checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          generate_release_notes: true
          draft: false
          prerelease: false
